# Generated by Django 2.2.5 on 2019-09-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190926_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='deadline',
            new_name='deadline_at',
        ),
    ]
